apiVersion: v1
kind: ConfigMap
metadata:
  name: manual-vfio-config
  namespace: sriov-network-operator
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "fh_sriov_up",
          "resourcePrefix": "fh.com",
          "selectors": {
            "drivers": ["vfio-pci"],
            "pfNames": ["ens7f0#0-1"],
            "rootDevices": ["0000:ca:00.0"]
          }
        },
        {
          "resourceName": "fh_sriov_cp",
          "resourcePrefix": "fh.com", 
          "selectors": {
            "drivers": ["vfio-pci"],
            "pfNames": ["ens7f0#2-3"],
            "rootDevices": ["0000:ca:00.0"]
          }
        }
      ]
    }
