---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  gnb.conf: |
    L1s = (
    {
      num_cc = 1;
    	tr_n_preference  = "nfapi";
      remote_n_address = "@VNF_IP_ADDRESS@"; // vnf addr
      local_n_address  = "@PNF_IP_ADDRESS@"; // pnf addr
      local_n_portc    = 50000; // pnf p5 port [!]
      remote_n_portc   = 50001; // vnf p5 port
      local_n_portd    = 50010; // pnf p7 port
      remote_n_portd   = 50011; // vnf p7 port
      prach_dtx_threshold = 130;
      pucch0_dtx_threshold = 80;
      pusch_dtx_threshold = 10;
      max_ldpc_iterations = 15;
      tx_amp_backoff_dB = 12; # needs to match O-RU configuration
      L1_rx_thread_core = @L1_RX_CORE@;
      L1_tx_thread_core = @L1_TX_CORE@; # relevant after merge of l1_tx_thread
      phase_compensation = 0; # needs to match O-RU configuration
    }
    );

    RUs = (
    {
      local_rf       = "no";
      nb_tx          = 4;
      nb_rx          = 4;
      att_tx         = 0;
      att_rx         = 0;
      bands          = [78];
      max_pdschReferenceSignalPower = -27;
      max_rxgain                    = 75;
      sf_extension                  = 0;
      eNB_instances  = [0];
      ru_thread_core = @RU_CORE@;
      sl_ahead       = 10;
      tr_preference  = "raw_if4p5"; # important: activate FHI7.2
      do_precoding   = 0; # needs to match O-RU configuration
    }
    );

    log_config :
    {
      global_log_level = "info";
      hw_log_level     = "info";
      phy_log_level    = "info";
      mac_log_level    = "info";
      rlc_log_level    = "info";
      pdcp_log_level   = "info";
      rrc_log_level    = "info";
      ngap_log_level   = "info";
      f1ap_log_level   = "info";
    };

    fhi_72 = {
      dpdk_devices = ("@C_PLANE_PCI_ADD@", "@U_PLANE_PCI_ADD@");
      dpdk_iova_mode = "{{ .Values.fhi72.dpdk_iova_mode }}";
      system_core = @SYSTEM_CORE@;
      io_core = @IO_CORE@;
      worker_cores = (@WORKER_CORE_LISTS@);
      du_addr = ("{{ .Values.multus.ruInterface.cPlaneMacAdd }}", "{{ .Values.multus.ruInterface.uPlaneMacAdd }}");
      ru_addr = ("{{ .Values.config.ruCPlaneMacAdd }}", "{{ .Values.config.ruUPlaneMacAdd }}");
      mtu = {{ .Values.multus.ruInterface.mtu }};
      file_prefix = "{{ .Values.fhi72.file_prefix }}";
      fh_config = ({
          {{- range $key, $value := .Values.fhi72.fh_config.timings }}
          {{- if kindIs "map" $value }}
          {{ $key }} = ({{ $value.min }}, {{ $value.max }});
          {{- else }}
          {{ $key }} = {{ $value }};
          {{- end }}
          {{- end }}
          ru_config = {
            {{- range $key, $value := .Values.fhi72.fh_config.ru_config }}
            {{ $key }} = {{ $value }};
            {{- end }}
          };
          prach_config = {
            {{- range $key, $value := .Values.fhi72.fh_config.prach_config }}
            {{ $key }} = {{ $value }};
            {{- end }}
          };
        });
    };

