apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: {{ .Chart.Name }}-cplane-{{ .Values.multus.ofh.ruName }}
  namespace:  {{ .Values.multus.ofh.sriovNetworkNamespace }}
spec:
  networkNamespace: {{ .Release.Namespace }}
  resourceName:  {{ .Values.multus.ofh.sriovResourceName }}
  vlan: {{ .Values.multus.ofh.vlan }}
  spoofChk: "off"
  trust: "on"
  capabilities: '{ "mac": true }'
---
# apiVersion: sriovnetwork.openshift.io/v1
# kind: SriovNetwork
# metadata:
#   name: {{ .Chart.Name }}-uplane-{{ .Values.multus.ofh.ruName }}
#   namespace:  {{ .Values.multus.ofh.sriovNetworkNamespace }}
# spec:
#   networkNamespace: {{ .Release.Namespace }}
#   resourceName:  {{ .Values.multus.ofh.sriovResourceName }}
#   vlan: {{ .Values.multus.ofh.vlan }}
#   spoofChk: "off"
#   trust: "on"
#   capabilities: '{ "mac": true }'
